version: "3.8"

services:
  # User service
  user-service:
    container_name: 'user_service'
    build:
      context: .
      dockerfile: services/user-service/Dockerfile.dev
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8001/" ]
      interval: 1m
      timeout: 3s
      start_period: 10s
      retries: 3
    ports:
      - '8001:8001'
    networks:
      - docker_net

  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - docker_net

  # Opentelemetry - jaeger, UI available on http://localhost:16686/
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: 'jaeger'
    restart: always
    ports:
      - '5775:5775/udp'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '5778:5778'
      - '16686:16686'
      - '14268:14268'
      - '9411:9411'
    networks:
      - docker_net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - docker_net

networks:
  docker_net:
