[application]
port = 8001
host = "user_service"
base_url = "localhost"
workers = 4
max_json_payload_size = 4096

[db]
host = "mongodb"
port = "27017"
database_name = "users"

[cache]
host = "redis"
port = "6379"

[tracer.jaeger]
host = "jaeger"
port = "6831"
