[application]
port = 8001
host = "user_service"
base_url = "localhost"
workers = 4
max_json_payload_size = 4096

[db]
user_name = "user"
password = "password"
host = "mongodb"
port = "27017"
database_name = "account"

[rate_limit]
burst_size = 5
frequency = 2

[tracer.jaeger]
url = "jaeger:6831"
